@keenomvictor- match:
    dependency_type: "all"
    update_type: "all"
def add(x, y):
    return x + y
def add(x, y):
    return x + y
pod 'FBSDKCoreKit', '~> 8.0.0'
pod 'FBSDKLoginKit', '~> 8.0.0'
pod 'FBSDKShareKit', '~> 8.0.0'
pod 'FBSDKGamingServiceKit', '~> 8.0.0'
Summary
Subject: Because you deserve to be celebrated—especially today! 💙
Message Id: <s4ctxd-07sfkm-ds@sendpulse.info>
Creation time: Sun, 19 Nov 2023 05:00:46 +0000 (Delivered after 3 seconds)
From: "Somebody from Breet" <support@breet.app>
To: <victorkeenom@thewebimagineers.onmicrosoft.com>

Received
Hop: 1
From: mx103.sendpulse.info (91.239.43.73)
By: DU6PEPF0000952A.mail.protection.outlook.com (10.167.8.11)
With: Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
Id: 15.20.7025.13
Via: Frontend Transport
Date: 11/18/2023 9:00:49 PM

Hop: 2
From: DU6PEPF0000952A.eurprd02.prod.outlook.com (2603:10a6:10:4bc:cafe::fb)
By: DUZPR01CA0135.outlook.office365.com (2603:10a6:10:4bc::6)
With: Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
Id: 15.20.7002.26
Via: Frontend Transport
Date: 11/18/2023 9:00:50 PM
Delay: 1 second
Percent: 33.333333333333336

Hop: 3
From: DUZPR01CA0135.eurprd01.prod.exchangelabs.com (2603:10a6:10:4bc::6)
By: PR3PR10MB3771.EURPRD10.PROD.OUTLOOK.COM (2603:10a6:102:47::22)
With: Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
Id: 15.20.7002.23
Date: 11/18/2023 9:00:50 PM
Delay: 0 seconds

Hop: 4
From: PR3PR10MB3771.EURPRD10.PROD.OUTLOOK.COM (2603:10a6:102:47::22)
By: AS8PR10MB6174.EURPRD10.PROD.OUTLOOK.COM
With: HTTPS
Date: 11/18/2023 9:00:52 PM
Delay: 2 seconds
Percent: 66.66666666666667

ForefrontAntiSpamReport
Country/Region: DE
Language: en
Spam Confidence Level: 5
Spam Filtering Verdict: SPM
IP Filter Verdict: NLI
HELO/EHLO String: mx103.sendpulse.info
PTR Record: mx103.sendpulse.info
Connecting IP Address: 91.239.43.73
Protection Policy Category: SPM
Spam rules: (13230031)(4636009)(230922051799003)(1690799017)(451199024)(166002)(356005)(7636003)(956004)(40140700001)(7596003)(83170400001)(118246002)(33964004)(6666004)(19627405001)(9686003)(6486002)(58800400005)(36756003)(7696005)(6506007)(7846003)(26005)(19810500001)(36736006)(6916009)(1096003)(42882007)(9316004)(66899024)(83380400001)(9036002)(76236004)(5660300002)(22186003)(336012)(76899018)(1406899027)(6326007)(12170700002)
Source header: CIP:91.239.43.73;CTRY:DE;LANG:en;SCL:5;SRV:;IPV:NLI;SFV:SPM;H:mx103.sendpulse.info;PTR:mx103.sendpulse.info;CAT:SPM;SFS:(13230031)(4636009)(230922051799003)(1690799017)(451199024)(166002)(356005)(7636003)(956004)(40140700001)(7596003)(83170400001)(118246002)(33964004)(6666004)(19627405001)(9686003)(6486002)(58800400005)(36756003)(7696005)(6506007)(7846003)(26005)(19810500001)(36736006)(6916009)(1096003)(42882007)(9316004)(66899024)(83380400001)(9036002)(76236004)(5660300002)(22186003)(336012)(76899018)(1406899027)(6326007)(12170700002);DIR:INB;
Unknown fields: DIR:INB;

AntiSpamReport
Bulk Complaint Level: 0
Source header: BCL:0;

Other
spf=pass (sender IP is 91.239.43.73) smtp.mailfrom=sendpulse.info; dkim=pass (signature was verified) header.d=breet.app;dmarc=pass action=none header.from=breet.app;compauth=pass reason=100
Pass (protection.outlook.com: domain of sendpulse.info designates 91.239.43.73 as permitted sender) receiver=protection.outlook.com; client-ip=91.239.43.73; helo=mx103.sendpulse.info; pr=C
multipart/alternative
1.0
bulk
369905:8322401:es:SP
202300@sendpulse.info
<support@breet.app>
826d9dbba892cfcf9c0df512b3c3e761@breet.app
postmaster@sendpulse.info
abuse@sendpulse.info
<http://s8322401.sendpul.se/unsubscribes/en/MzY5OTA1/da9bb22aa3ea24500ea4fc1738d1e985/h/3902472b1acfa86026d195a59ef54ae7?force=1>
v=1; a=rsa-sha256; c=relaxed/simple; d=breet.app;  i=@breet.app; q=dns/txt; s=sign; t=1700370049;  x=1700406049; h=subject : from : to : message-id : cc;  bh=ukNlj2TyNGPuR1cNV2GW1NRvOP0BjRbo4Nu6pX/1ktk=;  b=HmPBJeqdsgs5JRn4vBdjuC1AG+AUEfygFKKvEaeF6Frjy07DF6dKl4F3 tyc0+hFjEWe1ZrRpVluzfxCO5TUlcCDNIDlIOlW+KB2LxyHd2J79SeaAxr sIxiq4v3qYIuqqnpiJU4UcrmALia9Un04H06EZbVr/wgJfdJ0oWhBY/X0=
v=1; a=rsa-sha256; c=relaxed/simple; d=sendpulse.info;  i=@sendpulse.info; q=dns/txt; s=sign; t=1700370049;  x=1700406049; h=subject : from : to : message-id : cc;  bh=ukNlj2TyNGPuR1cNV2GW1NRvOP0BjRbo4Nu6pX/1ktk=;  b=bskzRYC+9WkLDgMFRMqf+64O2CXZbKPsVhHowBGCqVQUCL7SP4ORgry3 XMtOiyNetTwjFzriXb9hoIc6RbZamS/Of8qxkoJVjLuKSggzh8AvPRePc/ sC8jHqkZEKnjb0Xyt65sl+xJmPhETSAbqQgTyLNdFudb9cRBr2NOCJYik=
postmaster@sendpulse.info
19 Nov 2023 05:00:49.8366 (UTC)
OriginalSubmit
1:00:00:00.0000000
OriginalSubmit
2a61812c-8e44-46a4-ff03-08dbe8bc7fc7
0
ae471520-454b-4dae-8e87-0878db324b9c:0
Incoming
Email
DU6PEPF0000952A:EE_|PR3PR10MB3771:EE_|AS8PR10MB6174:EE_
DU6PEPF0000952A.eurprd02.prod.outlook.com
Anonymous
2a61812c-8e44-46a4-ff03-08dbe8bc7fc7
5
19 Nov 2023 05:00:49.6334 (UTC)
2a61812c-8e44-46a4-ff03-08dbe8bc7fc7
ae471520-454b-4dae-8e87-0878db324b9c
DU6PEPF0000952A.eurprd02.prod.outlook.com
Anonymous
Internet
PR3PR10MB3771
00:00:03.1468636
15.20.7002.024
ucf:0;jmr:0;auth:0;dest:J;OFR:SpamFilterAuthJ;ENG:(910001)(944506478)(944626604)(920097)(930097)(3100021)(140003);RF:JunkEmail;
wq2nMW1FfA8bMY8udHL24xtQfIRz0M8Hm6/P6XnkWRVE/kkB+HpHGaJ6OuTJipwm+/fkcZXL8HKSHcAb1BD+HqYr2mYzyIyAlFbN86d47qhcvGyK0jSPHPUD590iB4cgyN3FORE009XIDdQEsQIJ6W8w1fF69nMWQWZOlkN2hxB7bJyXAFWq9jJygWx0F3WcSn8thPVaFXeqALy8U+njec5ukPA+ilVaei2+BzfuYVXy6uoq12uBVcR4C/0c4bRNLLkbTPHZK9aO3TUmZbqnjF5OfKk6JzhgA3ndIR04+ia8hGpP+WOcZUcT6TbZ9aZ5XF7h8UZaGL/03MkYBN9TewAKgZ0dybhpCwpxBi4/RrCKndXtjcefO14hnleIku713vqpKmdZDABCjfErZFrCd+i892XQqebtOqLmSHrTvJ4L+6HlgqqqnZMuNRUoiW/lvxy6fK+i/ZUAMVF+XDaWntBR9eZvY9GeaS6pypP8GaPyImjYFXmcRD0ILdD7Q40wGiq4Kxs1B9XneY6sjEKDIBH+7rny3PPJDor3Y/x1pFUX1gA2XiBtCzuTPxDGdrM2BojojIH8drPZ4LnilrBABwUBKszvEfeGps1tIyNBHrFXE0xgN/iUm4uinrtCIzr+j+tNTOh3boG5r7TuTy74RbAOQ9umd2fKyjoPvzPVhsOwDaZV1ZEbpRuTDFawkRdgzddCwEwT3VdBRV7NDK90w4egKqGBdCLGomECrSFFSd8MfVghscVxZY68ZqGo6jJynFhCVres6MVEShq9ZX4Gu1tvcVcgI6PxC3hzeR3Oe4APkQd8R06/Bd1BQkc2KD9fNwRwEs/oBzEgJty7jaLKnZ4CGN+4nb0B+sv8Dt86xVXL+/qZ1cPxZbCtpAGVi95DD1Pco328XvrB0FC7sCcPfz9Nh9OiycWptdFA4QUcxqIMnynuVjyRjhXX7SX1if6MUCnxGmY2uO4iPsh27yXzAewccwXUqa0PpY4i9qSIzQv1VdDX1aYzRIv5Znb+sTJjimcyrzua/hwcUQxcapSqYFCtH4ZQGPRZIh9YWU8zNUfi4wtXIK0xvakKELhT3FDijZTQTu5axCluMu8T/aRAVFG+Wv5QXG0I/CxITfZTMwiiP79GSzO7hPFc9cfxOVtvBiux7KpZHLjOJXhrLYPCg+UYKICNlXvjL4WqXxG8LGcDX20W4AGiEQGphzZAdTgmhPRyt7ICGJd24cS39YTVPOhXRgJPMDS1Su4BBwg4NBVZMLhIhGwsz9LevjiDZWCLsB8pLdUbsQiE/+d2lEiRHid+679bRo+PaMHW9EBilFXMnDIo3KGv+ymH4lSG8VCnBnh9Zl2tN27AwlFBcixTqodDujel4gpl9KULRpAJenLswNRHv6FfQqt71WXPXgfPZvivo5nK0FAHgPAS5t8UNxHKElyA+0sP5FSpR+wto5YR+WRrtqMfH5dgXe/w74k3DrEyAotsdCloN/CHnTD7j+KqqVS7nbptaKHnXU6zE5uaCMVp1kCFtZrHrqlAvzppZwbrjdcq3H4VHFLNsDXlvzGWiyqNzUlWkhyFQMFKRA64GbfkjX+rlmFZMtm2G3ChKbeuB9jUXA8LW+BL+/PQkbGn6V/lYnwhtKmg51oOAwnfZumgv12YBluwtmXH328ZFrTGmjm2y/rarJyFJ5GBOiL/2bdBCbc0rIekFJZXDamRhJRq/7KcYKqWA/ZLAEzHFz5rtAVEfPPr4cYa47H5o8Su1XNNl1/YBB656epBq18/5Ifc1zslwImjMcsOiBfsXMPSELLDao1sC2TjkSnal9l+RxR9bc8/K+dKzVOyHV+1Tkit+qygR5HNJfFVGmNvHdtlDcV0hknGM5b788vGLdbmdkI0O3hzURk+NvDF8CKgy74zYKmPEHcKM11v7cQ9FSibwC4Q1le0QBWxNsNuuKn833/OE19h58+nn3jF2/vC0Hr8k4YuqvatWKGcVJ43NqD0PduXqSBYKEMSo+HWn2noCfxEs7ZXpMA65Rf1V+0H0LS8Qs6Au5jRAl9Blg+ZrEXlUOYnT0JU2i0U2+QRtPuhVqlA4F89Q5L7PDDSaaB5GfIgZ8IJtOnRm+xfAg5QEniyDj+p6HOvxKWMkWDPEtwzEjWUAStNko7wl6SfiAf3BnkOChXsznAqO0Z9WnAfwAdsAMgTKCkHbod+7VAK5Sad3EyhYWeYfPS3J85Ii8IHx5yF1uN0PQHAJzzNFSc3LxsALZvGybDkRHdO/u3mrTmavBZBu/F7wI9V6gW/N3X0MKrG7UaXRbXr/9dn6H1jsxE2VzTHVQayEqITr8KHpcEuHB0IDmK6qPVtJYNQ85qz+ilEX8LoryNZ6xpuJovk6HO0bLCcPIWs7rrB7bJ0suR2V6F9cDRFv2fvZLchI8h6rV9LW7u+8Th0hDXLToV2w7wha3UNZbjLo/sU+aS63Xk+zGfIEaY6AxsIEPrAOtVCZcc20A8NBKN2eDXB0N9naorA2REFts8586yVQNzBtEdDkyl1IOUUhy+IpQMHQFNQeXspNp9DINioJEGLcNVicK2ROc+WYsK1eJNB1MysTq+vwflH/aqXVljy68cY0giSRUiRfTQKnm8yoGcyOWDL
